FROM arm32v7/elixir:1.14-otp-25-alpine AS build

# install build dependencies
RUN \
  apk add --no-cache \
  build-base \
  npm \
  git \
  make \
  cmake \
  openssl-dev \ 
  ffmpeg-dev \
  clang-dev \
  vips-dev \
  libsrtp-dev

ARG VERSION
ENV VERSION=${VERSION}

ARG ERL_FLAGS
ENV ERL_FLAGS=$ERL_FLAGS

# Create build workdir
WORKDIR /app

# install hex + rebar
RUN mix local.hex --force && \
  mix local.rebar --force

# set build ENV
ENV MIX_ENV=prod
ENV VIX_COMPILATION_MODE=PLATFORM_PROVIDED_LIBVIPS

# install mix dependencies
COPY mix.exs mix.lock ./
COPY config config
COPY assets assets
COPY apps apps

RUN mix deps.get
RUN sed -i 's/-Werror//' deps/vix/c_src/Makefile
RUN mix deps.compile

RUN cd apps/ex_nvr_web/assets && npm install
RUN cd apps/ex_nvr_web && mix assets.deploy

# compile and build release

RUN mix do compile, release

# prepare release image
FROM alpine:3.17.0 AS app

# install runtime dependencies
RUN \
  apk add --no-cache \
  openssl \
  ncurses-libs \
  ffmpeg \
  clang \ 
  curl \
  vips \
  libsrtp

WORKDIR /app

RUN chown nobody:nobody /app

USER nobody:nobody

COPY --from=build --chown=nobody:nobody /app/_build/prod/rel/ex_nvr ./

ENV HOME=/app

EXPOSE 4000

HEALTHCHECK CMD curl --fail http://localhost:4000 || exit 1  

COPY --chown=nobody:nobody entrypoint.sh ./entrypoint.sh

RUN chmod +x entrypoint.sh

ENTRYPOINT ["./entrypoint.sh"]

CMD ["bin/ex_nvr", "start"]