openapi: 3.0.0
info:
  title: ExNVR API
  description: Manage ExNVR via API endpoints
  version: 0.1.0
servers:
  - url: 'http://localhost:4000'
paths:
  /api/users/login:
    post:
      summary: Login user
      description: |
        Login the user into the system

        The issued access token has a validity of `2 days`.
      operationId: login
      tags:
        - User
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
              required: [username, password]
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                    description: An access token to use to authorize subsequent requests
        '400':
          $ref: "#/components/responses/BadArg"
  /api/devices/{device_id}/recordings/{recording_id}/blob:
    get:
      summary: Get recording blob
      description: | 
        Download the video chunk with the specified `recording id` in the specified `device`
      operationId: getRecordingBlob
      tags:
        - Recording
      parameters:
        - $ref: '#/components/parameters/device_id'
        - $ref: '#/components/parameters/recording_id'
      responses:
        '200':
          description: Success
          content:
            video/mp4:
              schema:
                type: string
                format: binary
        '400':
          description: Not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: The error message
  /api/devices/{device_id}/hls/index.m3u8:
    get:
      summary: Start HLS streaming
      description: | 
        Start HLS live view streaming.

        The manifest will have two playlists, high quality video with resolution `1080x720` and 
        a low quality video with resolution `856x480`.
      operationId: startHlsStreaming
      tags:
        - Streaming
      parameters:
        - $ref: '#/components/parameters/device_id'
        - name: pos
          in: query
          description: |
            Start streaming from the given date time.

            If this `param` is provided, only high quality is enabled 
          schema:
            type: string
            format: date-time
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: string
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: opaque
  schemas:
    Error:
      type: object
      properties:
        code:
          type: string
          description: A unique error code
        description:
          type: string
          description: The description of the error
        details:
          type: object
          description: Other details related to the error.
  parameters:
    device_id:
      name: device_id
      description: The id of the device
      in: path
      required: true
      schema:
        type: string
        format: uuid
      example: d0d83123-b3af-48b0-b9ea-2569179a7517
    recording_id:
      name: recording_id
      description: The filename of the recording
      in: path
      required: true
      schema:
        type: string
      example: 11236565645.mp4
  responses:
    BadArg:
      description: Bad Arguments
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
security:
  - bearerAuth: []