version: '3'
services:
  ex_nvr:
    container_name: ex_nvr
    image: ghcr.io/evercam/ex_nvr:v0.6.0
    restart: always
    env_file:
      - .env
    ports:
      - 4000:4000
      - 8100:443
    volumes:
      - "/dev/shm:/dev/shm"
      - "/data/ex_nvr/database:/var/lib/ex_nvr"
      - "/data/ex_nvr/cert:/home/app/data/cert"
      - "/tmp:/tmp/sockets"