import Config

config :ex_nvr, env: :prod

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :ex_nvr, ExNVRWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, :api_client, ExNVR.Finch

config :logger, :console,
  level: :info,
  metadata: [:device_id, :user_id, :request_id],
  format: "$dateT$time $metadata[$level] $message\n"

config :membrane_core,
  enable_metrics: false

config :live_vue,
  ssr_module: LiveVue.SSR.NodeJS,
  ssr: false

sentry_enabled? = String.to_existing_atom(System.get_env("SENTRY_ENABLED", "false"))

if sentry_enabled? do
  root_source_code = [
    File.cwd!(),
    Path.join([File.cwd!(), "..", "rtsp"])
  ]

  config :sentry,
    release: "ex_nvr@0.19.1",
    report_deps: false,
    root_source_code_paths: root_source_code,
    context_lines: 5,
    environment_name: config_env(),
    enable_source_code_context: true,
    before_send: {ExNVR.Sentry, :before_send}
end

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
